### ISSUE TITLE
State structure 

### ISSUE THREAD

**Issue by r00bal** [DawidKrupski/goit-react-hw-02-feedback#1]
https://github.com/DawidKrupski/goit-react-hw-02-feedback/blob/a386ce6cc455c7653d3d5f1864616e67b698a456/src/components/Widget/Widget.js#L4-L11

W stanie trzymamy tylko niezbędne rzeczy. `total i positive` możesz juz sobie obliczyć na podstawie tego co w stanie się już znajduje

**Comment by DawidKrupski** [comment]
Poprawione
