### ISSUE TITLE
Repetition 

### ISSUE THREAD

**Issue by r00bal** [DawidKrupski/goit-react-hw-02-feedback#2]
https://github.com/DawidKrupski/goit-react-hw-02-feedback/blob/a386ce6cc455c7653d3d5f1864616e67b698a456/src/components/Widget/Widget.js#L17-L37

W każdej z tych funkcji nie potrzebnie powtarzasz 
```
 this.countTotalFeedback(); 
 this.countPositiveFeedbackPercentage(); 
```
Wystarczy sama zmiana good,bad,neutral i na podstawie zmiany stanu możesz obliczyć wartości dla total i positive.
Po każdej zmianie stanu komponent się re-renderuje.

Możesz obliczyć te wartości w metodzie render np.
```
 render() {
    const { good, neutral, bad } = this.state;
    const total = good + neutral + bad;
    const countPositiveFeedbackPercentage =
      total > 0 ? Math.round((good / total) * 100) : 0;
    return ( twój jsx )
```
albo poprzez wywołanie funkcji np. tworzysz w komponencie funkcje:
```
  countPositivePercentage() {
    const { good } = this.state;
    return Math.round((good / this.countTotalFeedback()) * 100);
  }
```
i wywołujesz ją już w returnie np.
```
return (
  <Component positive={countPositivePercentage} />
)
```

**Comment by DawidKrupski** [comment]
Poprawione
